version: '3.8'

services:
  anprvision-front-prod:
    container_name: anprvision-front-prod
    build:
      context: ../..
      dockerfile: angular/Dockerfile
      args:
        ENVIRONMENT: prod
        API_URL: ${API_URL}   # 👈 pasa la URL al build
    restart: always
    env_file:
      - .env
    ports:
      - "${FRONT_PORT}:80"
    networks:
      - anpr-net-prod
    labels:
      - com.anprvision.environment=prod

networks:
  anpr-net-prod:
    external: true

