name: anprvision-front-prod
version: "3.9"

services:
  # 🌐 Frontend Angular - PRODUCCIÓN
  anprvision-front-prod:
    container_name: anprvision-front-prod
    build:
      context: ../..              # raíz del proyecto Angular
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: production   # Angular build en modo prod
        API_URL: ${API_URL}       # URL pública del backend prod (HTTPS)
        API_HUB: ${API_HUB}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${FRONT_PORT}:80"        # Exposición HTTP (servida por NGINX)
    networks:
      - anpr-net-prod
    labels:
      - com.anprvision.environment=prod
      - com.anprvision.module=frontend

networks:
  anpr-net-prod:
    external: true
