version: '3.8'

services:
  anprvision-front-develop:
    container_name: anprvision-front-develop
    build:
      context: ../..
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: develop
        API_URL: ${API_URL}
    restart: always
    env_file:
      - .env
    ports:
      - "${FRONT_PORT}:80"
    volumes:
      - ../../nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf
    networks:
      - anpr-net-develop
    labels:
      - com.anprvision.environment=develop

networks:
  anpr-net-develop:
    external: true

