version: '3.8'

services:
  anprvision-front-qa:
    container_name: anprvision-front-qa
    build:
      context: ../..
      dockerfile: angular/Dockerfile
      args:
        ENVIRONMENT: qa
        API_URL: ${API_URL}
    restart: always
    env_file:
      - .env
    ports:
      - "${FRONT_PORT}:80"
    volumes:
      - ../../nginx.local.conf:/etc/nginx/conf.d/default.conf
    networks:
      - anpr-net-qa
    labels:
      - com.anprvision.environment=qa

networks:
  anpr-net-qa:
    external: true

