name: anprvision-front-qa
version: "3.9"

services:
  # 🌐 Frontend Angular - QA
  anprvision-front-qa:
    container_name: anprvision-front-qa
    build:
      context: ../..             # raíz del proyecto Angular
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: production  # Angular build usa configuración prod
        API_URL: ${API_URL}      # URL del backend QA
        API_HUB: ${API_HUB}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${FRONT_PORT}:80"       # puerto host → contenedor
    networks:
      - anpr-net-qa
    labels:
      - com.anprvision.environment=qa
      - com.anprvision.module=frontend

networks:
  anpr-net-qa:
    external: true
