version: '3.8'

services:
  anprvision-front-staging:
    container_name: anprvision-front-staging
    build:
      context: ../..
      dockerfile: angular/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "${FRONT_PORT}:80"
    networks:
      - anprvision_network
    labels:
      - com.anprvision.environment=staging

networks:
  anprvision_network:
    external: true
