name: anprvision-front-staging
version: "3.9"

services:
  # 🌐 Frontend Angular - STAGING
  anprvision-front-staging:
    container_name: anprvision-front-staging
    build:
      context: ../..             # raíz del proyecto Angular
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: production  # Angular build usa configuración prod
        API_URL: ${API_URL}      # URL del backend staging
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${FRONT_PORT}:80"       # puerto host → contenedor
    networks:
      - anpr-net-staging
    labels:
      - com.anprvision.environment=staging
      - com.anprvision.module=frontend

networks:
  anpr-net-staging:
    external: true
